/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pointofsalebillingmodule;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sanjeet
 */
public class BillController extends javax.swing.JFrame {

    private ArrayList<Product> billItemsList;
    /**
     * Creates new form BillingController
     * @param billItemList
     */
    public BillController(ArrayList<Product> billItemsList) {
        initComponents();
        this.billItemsList = new ArrayList<>();
        this.billItemsList = billItemsList;
        
        billItemsTable();
        
        updateLabels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        billItemsScroll = new javax.swing.JScrollPane();
        billItemsTable = new javax.swing.JTable();
        taxLabel = new javax.swing.JLabel();
        taxPercentage = new javax.swing.JLabel();
        taxAmount = new javax.swing.JLabel();
        totalAmount = new javax.swing.JLabel();
        totalLabel1 = new javax.swing.JLabel();
        taxAmont = new javax.swing.JLabel();
        totalLabel2 = new javax.swing.JLabel();
        totalAmount1 = new javax.swing.JLabel();
        totalItemLabel = new javax.swing.JLabel();
        totalItems = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        billItemsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        billItemsScroll.setViewportView(billItemsTable);

        taxLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        taxLabel.setForeground(new java.awt.Color(0, 51, 51));
        taxLabel.setText("Tax:");

        taxPercentage.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        taxPercentage.setForeground(new java.awt.Color(0, 51, 51));
        taxPercentage.setText(" %13");

        taxAmount.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        taxAmount.setText("tax :");

        totalAmount.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        totalAmount.setForeground(new java.awt.Color(0, 0, 204));
        totalAmount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalAmount.setText("$20.00");

        totalLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        totalLabel1.setForeground(new java.awt.Color(0, 0, 204));
        totalLabel1.setText("total :");

        taxAmont.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        taxAmont.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        taxAmont.setText("$4.99");

        totalLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        totalLabel2.setForeground(new java.awt.Color(255, 0, 51));
        totalLabel2.setText("Bill Total :");

        totalAmount1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        totalAmount1.setForeground(new java.awt.Color(255, 0, 51));
        totalAmount1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalAmount1.setText("$24.99");

        totalItemLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        totalItemLabel.setText("Total Items:");

        totalItems.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        totalItems.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(billItemsScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 866, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(totalLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(taxAmount))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(taxLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(taxPercentage)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(totalLabel1)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(totalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(taxAmont, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(totalAmount1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(totalItemLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(totalItems)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalItemLabel)
                    .addComponent(totalItems))
                .addGap(32, 32, 32)
                .addComponent(billItemsScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(taxLabel)
                    .addComponent(taxPercentage)
                    .addComponent(totalAmount)
                    .addComponent(totalLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(taxAmount)
                    .addComponent(taxAmont))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalLabel2)
                    .addComponent(totalAmount1))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane billItemsScroll;
    private javax.swing.JTable billItemsTable;
    private javax.swing.JLabel taxAmont;
    private javax.swing.JLabel taxAmount;
    private javax.swing.JLabel taxLabel;
    private javax.swing.JLabel taxPercentage;
    private javax.swing.JLabel totalAmount;
    private javax.swing.JLabel totalAmount1;
    private javax.swing.JLabel totalItemLabel;
    private javax.swing.JLabel totalItems;
    private javax.swing.JLabel totalLabel1;
    private javax.swing.JLabel totalLabel2;
    // End of variables declaration//GEN-END:variables


 
    private void billItemsTable(){
        
        String columns[] = {"Bill Items", "Qty", "Price"};
        DefaultTableModel billItemsTableModel = new DefaultTableModel(columns, this.billItemsList.size());
        Object tableRow = new Object[3];
        for(int i=0; i< this.billItemsList.size(); i++){
        }
    
    }
    
    private void updateLabels(){
    
    }


}
